basicauth:
  enabled: true
  user: 
    valueFrom:
      secretKeyRef:
        name: wolfey-login
        key: username
  password: 
    valueFrom:
      secretKeyRef:
        name: wolfey-login
        key: password

webhook:
  enabled: true