apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ui-ingress
  namespace: observability
spec:
  rules:
  - host: "jaeger.wolfeydev.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jaeger-query
            port:
              number: 80