apiVersion: networking.k8s.io/v1
kind: Ingress
namespace: observability
metadata:
  name: jaeger-ingress
spec:
  rules:
  - host: "jaeger.wolfeydev.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jaeger-service
            port:
              number: 8080