apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signoz-ui-ingress
  namespace: observability
spec:
  rules:
  - host: "signoz.wolfeydev.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: signoz-frontend
            port:
              number: 3301