apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-collector-ingress
  namespace: observability
spec:
  rules:
  - host: "otel-collector.wolfeydev.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: otel-collector-opentelemetry-collector
            port:
              number: 4318