apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "TCP"
spec:
  rules:
  - host: redis.wolfeydev.com
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: redis
            port:
              number: 6379