apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: redis-gateway
spec:
parentRefs:
  - name: example-gateway
  hostnames:
  - "redis.example.com"
  rules:
  - backendRefs:
    - name: redis-service
      port: 6379