apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
spec:
  rules:
  - host: redis.wolfeydev.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
          backend:
            service:
              name: redis-service
              port:
                number: 6379
