apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: redis-ingress
spec:
  rules:
  - host: redis.wolfeydev.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          serviceName: redis-service
          servicePort: 6739
